### ISSUE TITLE
North Carolina isn't a street

### ISSUE THREAD

**Issue by Reno-Greenleaf** [datamade/usaddress#126]
Given a line "North Carolina" (without details), the result is:
[(u'North', 'StreetNamePreDirectional'), (u'Carolina', 'StreetName')]

**Comment by jeancochrane** [comment]
Hey @Reno-Greenleaf,

True enough – although if your goal is just to parse state names isolated from context, this probably isn't the right library to use. Since I'm not convinced this is a problem with usaddress, I'm going to close this issue for now. But feel free to reopen or make a new issue if you want to make an argument for handling cases like this.
