### ISSUE TITLE
crashing on: 'Pier 39 lot 12'

### ISSUE THREAD

**Issue by mtourne** [datamade/usaddress#139]
RepeatedLabelError: 
ERROR: Unable to tag this string because more than one area of the string has the same label

ORIGINAL STRING:  Pier 39 lot 12
PARSED TOKENS:    [(u'Pier', 'OccupancyType'), (u'39', 'OccupancyIdentifier'), (u'lot', 'OccupancyType'), (u'12', 'OccupancyIdentifier')]
UNCERTAIN LABEL:  OccupancyType

When this error is raised, it's likely that either (1) the string is not a valid person/corporation name or (2) some tokens were labeled incorrectly

**Comment by fgregg** [comment]
How do you think this should be tagged?

**Comment by mtourne** [comment]
that I'm not sure, but it does raise an error that asks that you report it (if I remember correctly).

**Comment by jeancochrane** [comment]
Hey @mtourne,

This should point to a [Pier 39 parking lot](https://goo.gl/maps/C2bisBRrw5M2), right? It's an edge case, so I'm not terribly certain, but my guess is that it should be classified like so:

| String | Parsed type |
| ------ | ------------ |
| Pier | LandmarkName |
| 39 | LandmarkName |
| lot | SubaddressType |
| 12 | SubaddressIdentifier|

(You can find our general classification guidelines [in our docs](http://usaddress.readthedocs.io/en/latest/#details), and you can read the official US data standard for addresses [here](http://www.urisa.org/clientuploads/directory/GMI/Professional%20Practice/Address%20Standard/AddressStandard_Approved_Apr11_02Content.pdf).)

We ask users to report errors so that we can improve our training data. My guess is that we don't have many (if any) examples of piers or parking lots to train the model on right now, so it's getting confused. If you're parsing a lot of addresses for piers/parking lots we'd be happy to incorporate them as training data – just let us know! Otherwise I'll close this.

**Comment by jeancochrane** [comment]
Hi @mtourne,

It's been a week, so I'm going to assume this isn't a pressing need. If you wind up parsing a lot of pier addresses and the model continues to fail, feel free to open up a new issue and we can look into it.
