### ISSUE TITLE
Subaddress parsing (Address Ranges)

### ISSUE THREAD

**Issue by chall8908** [datamade/usaddress#156]
I'm working with a dataset that contains a lot of address ranges.  I did a quick scan of the issues and didn't see anyone discussing these kinds of addresses.

For example:
````
>>> usaddress.tag('4120-4140 Annapolis Rd, Baltimore, MD 21227')
(OrderedDict([('AddressNumber', u'4120-4140'), ('StreetName', u'Annapolis'), ('StreetNamePostType', u'Rd'), ('PlaceName', u'Baltimore'), ('StateName', u'MD'), ('ZipCode', u'21227')]), 'Street Address')
````

In this case, per the URISA documentation, I might expect the Address Number to be some type of Subaddress, given one of their definitions of a "Complete Subaddress" is "Two Complete Address Numbers, separated by a hyphen, and followed by a Complete Street Name (in the case of a Two Number Address Range)".

Right now, I'm leaning towards usaddress' current behavior being the most correct and that I should handle the distinction myself, but I wanted to open the discussion.

**Comment by jeancochrane** [comment]
Good catch! Going by the standard, we could certainly describe '4120-4140' as a "Complete Subaddress." But I'm also not sure that this is a category that would make sense for us. The additional examples on p. 81 list a lot of different sets of tokens as "Complete Subaddresses," including "Complete Street Name" and "Complete Landmark Name." It seems to me that "Complete Subaddress" describes a larger group of tokens than we're interested in, since we want to parse down to the most basic elements of the address – and it's also substantially different from `SubaddressType`, which is the most similar kind of token that we currently support.

Something to keep an eye on for now. If you wind up finding more evidence that we should make a new type for `CompleteSubaddress` I'd be happy to hear it.

**Comment by jeancochrane** [comment]
Seems like this discussion hasn't quite caught on, so I'm closing this for now. @chall8908, feel free to reopen if you want to make the case for a `CompleteSubaddress` type.
