### ISSUE TITLE
Support Python 3.x

### ISSUE THREAD

**Issue by qidanrui** [datamade/usaddress#320]
The usaddress library only supports Python 2.7, which is because the `probableparsing` library only support Python 2.7 (https://pypi.org/project/probableparsing/). 
Remove this library or incorporate the code of `probableparsing` will solve this problem and make usaddress support Python 3.x.

**Comment by mlissner** [comment]
It's pretty sad around here:

 - This issue is asking for python 3 support (I can confirm that it works in 3.8 FWTW)
 - A [PR to add Python 3.7](https://github.com/datamade/usaddress/pull/267)
 - A [bug](https://github.com/datamade/usaddress/issues/314) explaining that python 3.10 doesn't work and suggesting there's a PR to fix it (but no PR seems to exist).
 - Forks adding better 3.x support
 - A forks [fixing the dependency on python-crfsuite](https://github.com/MicahLyle/usaddress/commit/9f25055b5adbe108e2ed6367552849d07d0e48ca)

This was a really great library and one that my organization depended on for parsing attorney addresses. Unfortunately, unless it's maintained somehow, we'll have to drop support for the feature, which is a bummer. 

Is there any way we can get this moving again? @fgregg, maybe you have some ideas? I'd offer to take over the package at FLP, but we don't really have the expertise. 

I think all it really needs is a fix to the crfsuite thing and a few tweaks to anywhere it mentions python 2.7, and it'd be ready to roll.


Sad to come here and see all the forks adding support for Python 3+. 

Hm, I've been running usaddress in production in Python 3.8 for quite a while. I'm upgrading to python 3.10, however and having issues due to the reliance on

**Comment by fgregg** [comment]
hi @mlissner , this is a really shitty way of interacting with open source projects

**Comment by mlissner** [comment]
Sorry, I don't mean to lay out all these problems and insult the good work here, but at the same time, it does look like the project is abandoned. There are a number of bugs, PRs, and forks related to python 3, and there hasn't been a commit here for four years aside from a readme tweak.

I'd love to get this fixed up again, but it's not an area where I have expertise. Usually that's what I do when something I rely on breaks or needs a tweak, but I can't do that here, I don't think.

What's a better way forward if the project is still maintained?

**Comment by mlissner** [comment]
That might work. I'll get in touch via email.

**Comment by fgregg** [comment]
3,10 works now
