### ISSUE TITLE
ValueError when tagging "1919 W. Taylor (m/c 525) Rm. 128"

### ISSUE THREAD

**Issue by derekeder** [datamade/usaddress#78]
```python
usaddress.tag("1919 W. Taylor (m/c 525) Rm. 128 ")

> ValueError: More than one area of address has the same label
```

**Comment by cathydeng** [comment]
I just tried this w/ the most recent usaddress version on pip (0.3.3) and it worked fine:

usaddress.tag('1919 W. Taylor (m/c 525) Rm. 128')
(OrderedDict([('AddressNumber', '1919'), ('StreetNamePreDirectional', 'W.'), ('StreetName', 'Taylor'), ('SubaddressType', '(m/c'), ('SubaddressIdentifier', '525)'), ('OccupancyType', 'Rm.'), ('OccupancyIdentifier', '128')]), 'Street Address')

re: the error - for the tag method, we assume that tokens w/ the same label should be consecutive in properly labeled addresses (e.g. StreetName-StreetName-StreetType is valid, while StreetName-StreetType-StreetName is likely to have been improperly labeled) since we are concatenating tokens w/ the same label

how about keeping this assumption & error, & for the bulk address parse, just returning empty columns for addresses that return this error? or, adding an output column for addresses that couldn't be tagged, and putting the entire un-taggable raw address string there?

**Comment by derekeder** [comment]
@cathydeng yah I'm handling these with a try/except just in case
